### ISSUE TITLE
Provide a Service Bus Event Consumer Host for integration testing

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.eventgrid#29]
## Situation
**Describe the bug**
HybridConnectionHost does not support running in parallel. This means that if 2 builds are using the same Hybrid Connection they will receive each other's request.

**To Reproduce**
1. Trigger first CI
2. Trigger second CI

**Expected behavior**
This kind of makes sense but we should investigate if we could receive the events on both CIs or document this as a known issue and using separate Hybrid Connections are advised.

**Conclusion**
Using Hybrid Connections is not the correct approach for running integration tests in parallel.

## New integration testing approach
An alternative approach is to switch to Azure Service Bus Topics where a process (be it function/Logic App) queues every event as-is on a topic.

Our new host will then:
1. Create a new subscription with filter `1=1`
2. Consume all messages as we do today
3. Delete his temporary subscription when it closes

This should allow us to run in parallel and flow the events inside our tests.

### Schematic overview
![untitled diagram](https://user-images.githubusercontent.com/4345663/47565095-91ed4c80-d927-11e8-8ccb-8e41c909660e.png)

### Task list
- [x] Create new host that uses this appraoch
- [x] Provide documentation on how it works
- [x] Deprecate old host

**Comment by tomkerkhove** [comment]
This is not supported by Azure Relay where every request will be load balanced across all receivers. This means that the current setup is only going to work if there is only one receiver.

Going to look for alternatives.

**Comment by tomkerkhove** [comment]
# Proposal
An alternative approach is to switch to Azure Service Bus Topics where a process (be it function/Logic App) queues every event as-is on a topic.

Our new host will then:
1. Create a new subscription with filter `1=1`
2. Consume all messages as we do today
3. Delete his temporary subscription when it closes

This should allow us to run in parallel and flow the events inside our tests.

## Schematic overview
![untitled diagram](https://user-images.githubusercontent.com/4345663/47565095-91ed4c80-d927-11e8-8ccb-8e41c909660e.png)

**Comment by tomkerkhove** [comment]
I'll POC this approach as it sounds feasible.

**Comment by tomkerkhove** [comment]
Updated issue with new appraoch and tasklist

**Comment by tomkerkhove** [comment]
Closed via #49
